### ISSUE TITLE
Cannot navigate to subdirectories using file dialog

### ISSUE THREAD

**Issue by ncomendant** [rewin123/space_editor#148]
When selecting a prefab or gltf to load, navigating to subdirectories in the file dialog has no effect.

Here is the relevant code for `gltf_dialog`:
```rust
// from bottom_menu.rs
let mut need_move_to_default_dir = false;
if let Some(path) = gltf_dialog.path() {
    if let Some(path) = path.to_str() {
        if !path.contains("assets") {
            need_move_to_default_dir = true;
        }
    } else {
        need_move_to_default_dir = true;
    }
} else {
    need_move_to_default_dir = true; // <-- COMMENTING THIS OUT FIXES THE ISSUE
}
if need_move_to_default_dir {
    gltf_dialog.set_path("assets/");
}
```
The problem is that `FileDialog::path()` gets the path of the _selected_ file. After a subdirectory is chosen, `gltf_dialog.path()` returns `None`, which puts us right back into `/assets`. `FileDialog` does not seem to have a way to get the current directory being shown.

If you comment out the line I noted earlier, it works! However, the user would be able to navigate to other directories too.

**Comment by rewin123** [comment]
Thanks for the bug report. I will try to fix it today

**Comment by MickHarrigan** [comment]
I just did a little digging in the `egui_file` source and found that the `FileDialog::path()` function does not actually use the path that the window is looking at, but the selected file.

I have a PR over there to add a new method for it and on my fork I am about to push to I have a small change that should address all the concerns otherwise.

**Comment by ncomendant** [comment]
Confirmed fixed, thanks!
